### ISSUE TITLE
Can we update ecma262 to the latest spec?

### ISSUE THREAD

**Issue by F3n67u** [kaist-plrg/jiset#221]
I wanna debug private field but the debugger says it doesn't recognize it. I think it is because our ecma262 version is not the latest.

Could we update ecma262 to the latest spec?

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/12343178/176174271-10837d14-1681-4316-9543-148ccfd533d0.png">

**Comment by jhnaldo** [comment]
Hi @F3n67u, I'm one of the main developers of JISET. If you want to update the version of ecma262 in JISET, please use the following command:
```bash
$ jiset gen-model -extract:version=es2022
```

By the way, we rebranded JISET in a new project called [ESMeta](https://github.com/es-meta/esmeta). We recommend using this rebranded version because we will no longer maintain JISET. If you want to use the same debugger feature in ESMeta, please read the README file in the [ESMeta](https://github.com/es-meta/esmeta) repository.

**Comment by F3n67u** [comment]
> We recommend using this rebranded version because we will no longer maintain JISET. 

Thanks for your info. Could you add this info in README of jiset?

**Comment by jhnaldo** [comment]
Sure, I just added a warning message in the README file as follows:
> **Warning** - This repository is no longer maintained. Instead, please use [ESMeta](https://github.com/es-meta/esmeta), a rebranded version of JISET.
